"""delete_content1

Revision ID: 6b2e9de307aa
Revises: 7bfbe2468a3d
Create Date: 2021-11-30 15:52:19.614475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b2e9de307aa'
down_revision = '7bfbe2468a3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'content1')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('content1', sa.TEXT(), server_default=sa.text("('')"), nullable=False))
    # ### end Alembic commands ###
