"""first

Revision ID: 748beda80d64
Revises: 
Create Date: 2021-11-29 16:52:20.078688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '748beda80d64'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.String(length=20), nullable=False))
    op.add_column('user', sa.Column('password', sa.String(length=100), nullable=False))
    op.drop_column('user', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.VARCHAR(length=20), nullable=True))
    op.drop_column('user', 'password')
    op.drop_column('user', 'username')
    # ### end Alembic commands ###
