"""add_content1

Revision ID: 7bfbe2468a3d
Revises: be62bcc01526
Create Date: 2021-11-30 15:49:45.771778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bfbe2468a3d'
down_revision = 'be62bcc01526'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('content1', sa.Text(), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'content1')
    # ### end Alembic commands ###
